# Import libraries and data

In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
df = pd.read_csv('/Users/marina/Desktop/final_project/data/raw/okcupid_profiles .csv')
#data/raw/okcupid_profiles .csv

# Explore data

essay0- My self summary - my_summary
essay1- What I’m doing with my life- doing_what
essay2- I’m really good at - good_at
essay3- The first thing people usually notice about me - noticed_for
essay4- Favorite books, movies, show, music, and food - favourites
essay5- The six things I could never do without - basic_six
essay6- I spend a lot of time thinking about - think_about
essay7- On a typical Friday night I am - typical_friday
essay8- The most private thing I am willing to admit - most_private
essay9- You should message me if... - message_if

In [3]:
df.info()
#https://www.kaggle.com/datasets/andrewmvd/okcupid-profiles
#see https://www.kaggle.com/andrewmvd/okcupid-profiles/discussion/183145 for details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   age          59946 non-null  int64  
 1   status       59946 non-null  object 
 2   sex          59946 non-null  object 
 3   orientation  59946 non-null  object 
 4   body_type    54650 non-null  object 
 5   diet         35551 non-null  object 
 6   drinks       56961 non-null  object 
 7   drugs        45866 non-null  object 
 8   education    53318 non-null  object 
 9   ethnicity    54266 non-null  object 
 10  height       59943 non-null  float64
 11  income       59946 non-null  int64  
 12  job          51748 non-null  object 
 13  last_online  59946 non-null  object 
 14  location     59946 non-null  object 
 15  offspring    24385 non-null  object 
 16  pets         40025 non-null  object 
 17  religion     39720 non-null  object 
 18  sign         48890 non-null  object 
 19  smok

In [31]:
df['age'].unique()


array([ 22,  35,  38,  23,  29,  32,  31,  24,  37,  28,  30,  39,  33,
        26,  27,  20,  25,  40,  36,  21,  34,  43,  46,  41,  42,  45,
        18,  55,  50,  59,  44,  48,  54,  51,  62,  52,  19,  58,  66,
        53,  63,  47,  49,  61,  60,  57,  56,  65,  64,  68, 110,  69,
        67, 109])

In [5]:
df['speaks'].unique()

array(['english', 'english (fluently), spanish (poorly), french (poorly)',
       'english, french, c++', ...,
       'english (fluently), hindi (poorly), french (poorly), tamil (okay), spanish (poorly)',
       'english (fluently), french (poorly), japanese (poorly), latin (poorly)',
       'english (fluently), french, farsi'], dtype=object)

# Clean column names

In [6]:

df.columns = df.columns.str.lower().str.replace(' ', '')

# Column drinks, diet, drugs, education, ethnicity,height,income,job,offspring,pets,religion,sign,smokes,speaks an all essays

In [7]:
# List of columns to fill NaN values with 'rather not say'
columns_to_fill = [
    'drugs', 'education', 'ethnicity', 'height', 'income', 'job', 
    'offspring', 'pets', 'religion', 'sign', 'smokes', 'speaks', 
    'essay0', 'essay1', 'essay2', 'essay3', 'essay4', 'essay5', 
    'essay6', 'essay7', 'essay8', 'essay9','drinks','diet',
    'body_type',
]

# Fill NaN values with 'rather not say'
df[columns_to_fill] = df[columns_to_fill].fillna('rather not say')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59946 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   age          59946 non-null  int64 
 1   status       59946 non-null  object
 2   sex          59946 non-null  object
 3   orientation  59946 non-null  object
 4   body_type    59946 non-null  object
 5   diet         59946 non-null  object
 6   drinks       59946 non-null  object
 7   drugs        59946 non-null  object
 8   education    59946 non-null  object
 9   ethnicity    59946 non-null  object
 10  height       59946 non-null  object
 11  income       59946 non-null  int64 
 12  job          59946 non-null  object
 13  last_online  59946 non-null  object
 14  location     59946 non-null  object
 15  offspring    59946 non-null  object
 16  pets         59946 non-null  object
 17  religion     59946 non-null  object
 18  sign         59946 non-null  object
 19  smokes       59946 non-nu

# Clean column age 2 wrong values

In [34]:
# Delete rows where 'age' is greater than 100 outliers or mistakes
df = df[df['age'] <= 100]

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59944 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   age          59944 non-null  int64  
 1   status       59944 non-null  object 
 2   sex          59944 non-null  object 
 3   orientation  59944 non-null  object 
 4   body_type    54649 non-null  object 
 5   diet         35550 non-null  object 
 6   drinks       56961 non-null  object 
 7   drugs        45865 non-null  object 
 8   education    53317 non-null  object 
 9   ethnicity    54266 non-null  object 
 10  height       59941 non-null  float64
 11  income       59944 non-null  int64  
 12  job          51747 non-null  object 
 13  last_online  59944 non-null  object 
 14  location     59944 non-null  object 
 15  offspring    24384 non-null  object 
 16  pets         40025 non-null  object 
 17  religion     39719 non-null  object 
 18  sign         48889 non-null  object 
 19  smokes   

# Clean column location and create 2 new ones: city and state

In [35]:
df1=df.copy()

# Check which rows do not contain a comma
no_comma_rows = df[~df['location'].str.contains(', ')]

print("Rows with no comma in 'location':")
print(no_comma_rows)

Rows with no comma in 'location':
Empty DataFrame
Columns: [age, status, sex, orientation, body_type, diet, drinks, drugs, education, ethnicity, height, income, job, last_online, location, offspring, pets, religion, sign, smokes, speaks, essay0, essay1, essay2, essay3, essay4, essay5, essay6, essay7, essay8, essay9]
Index: []

[0 rows x 31 columns]


In [36]:
# Check which rows do not contain a comma
no_comma_rows = df[~df['location'].str.contains(',')]
print("Rows with no comma in 'location':")
print(no_comma_rows)

# Define a function to split the 'location' column
def split_location(location):
    parts = location.split(', ')
    if len(parts) == 2:
        return parts[0], parts[1]
    else:
        return location, None

# Apply the split function and create new columns
df[['city', 'state']] = df['location'].apply(lambda x: pd.Series(split_location(x)))

# Display the updated DataFrame
print("Updated DataFrame:")
print(df)

Rows with no comma in 'location':
Empty DataFrame
Columns: [age, status, sex, orientation, body_type, diet, drinks, drugs, education, ethnicity, height, income, job, last_online, location, offspring, pets, religion, sign, smokes, speaks, essay0, essay1, essay2, essay3, essay4, essay5, essay6, essay7, essay8, essay9]
Index: []

[0 rows x 31 columns]
Updated DataFrame:
       age     status sex orientation       body_type               diet  \
0       22     single   m    straight  a little extra  strictly anything   
1       35     single   m    straight         average       mostly other   
2       38  available   m    straight            thin           anything   
3       23     single   m    straight            thin         vegetarian   
4       29     single   m    straight        athletic                NaN   
...    ...        ...  ..         ...             ...                ...   
59941   59     single   f    straight             NaN                NaN   
59942   24     single 

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59944 entries, 0 to 59945
Data columns (total 33 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   age          59944 non-null  int64 
 1   status       59944 non-null  object
 2   sex          59944 non-null  object
 3   orientation  59944 non-null  object
 4   body_type    59944 non-null  object
 5   diet         59944 non-null  object
 6   drinks       59944 non-null  object
 7   drugs        59944 non-null  object
 8   education    59944 non-null  object
 9   ethnicity    59944 non-null  object
 10  height       59944 non-null  object
 11  income       59944 non-null  int64 
 12  job          59944 non-null  object
 13  last_online  59944 non-null  object
 14  location     59944 non-null  object
 15  offspring    59944 non-null  object
 16  pets         59944 non-null  object
 17  religion     59944 non-null  object
 18  sign         59944 non-null  object
 19  smokes       59944 non-null  o

In [13]:
# rows where 'state' is null
rows_with_null_state = df[df['state'].isnull()][['location', 'city', 'state']]
print(rows_with_null_state)

# Fill NaN value 
df.loc[42438, 'state'] = 'vancouver'

# change
print(df.loc[42438, ['location', 'city', 'state']])

                                  location  \
42438  vancouver, british columbia, canada   

                                      city state  
42438  vancouver, british columbia, canada  None  
location    vancouver, british columbia, canada
city        vancouver, british columbia, canada
state                                 vancouver
Name: 42438, dtype: object


In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59944 entries, 0 to 59945
Data columns (total 31 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   age          59944 non-null  int64 
 1   status       59944 non-null  object
 2   sex          59944 non-null  object
 3   orientation  59944 non-null  object
 4   body_type    59944 non-null  object
 5   diet         59944 non-null  object
 6   drinks       59944 non-null  object
 7   drugs        59944 non-null  object
 8   education    59944 non-null  object
 9   ethnicity    59944 non-null  object
 10  height       59944 non-null  object
 11  income       59944 non-null  int64 
 12  job          59944 non-null  object
 13  last_online  59944 non-null  object
 14  location     59944 non-null  object
 15  offspring    59944 non-null  object
 16  pets         59944 non-null  object
 17  religion     59944 non-null  object
 18  sign         59944 non-null  object
 19  smokes       59944 non-null  o

In [15]:
df['income'].unique()

array([     -1,   80000,   20000,   40000,   30000,   50000,   60000,
       1000000,  150000,  100000,  500000,   70000,  250000])

# Convert column last_online to date time format. Also new column date and time.

In [16]:
df1['last_online'].unique()

array(['2012-06-28-20-30', '2012-06-29-21-41', '2012-06-27-09-10', ...,
       '2012-06-02-08-16', '2012-02-17-20-44', '2012-06-14-16-51'],
      dtype=object)

In [38]:
# Convert 'last_online' to datetime format
df1['last_online'] = pd.to_datetime(df1['last_online'], format='%Y-%m-%d-%H-%M')

# Create new columns for date and time
df1['last_online_date'] = df1['last_online'].dt.date
df1['last_online_time'] = df1['last_online'].dt.time

#print(df1)

In [39]:
#df1.info()

# Clean salary column

In [40]:
df['income'].unique()

array([     -1,   80000,   20000,   40000,   30000,   50000,   60000,
       1000000,  150000,  100000,  500000,   70000,  250000])

In [41]:
# Count rows where 'income' values are less than zero
count_negative_income = (df['income'] < 0).sum()

print(f"Number of rows with 'income' less than zero: {count_negative_income}")

Number of rows with 'income' less than zero: 48440


In [21]:
df1=df.copy()

In [42]:
df1['job'].unique()

array(['transportation', 'hospitality / travel', nan, 'student',
       'artistic / musical / writer', 'computer / hardware / software',
       'banking / financial / real estate', 'entertainment / media',
       'sales / marketing / biz dev', 'other', 'medicine / health',
       'science / tech / engineering', 'executive / management',
       'education / academia', 'clerical / administrative',
       'construction / craftsmanship', 'rather not say',
       'political / government', 'law / legal services', 'unemployed',
       'military', 'retired'], dtype=object)

In [44]:
# Filter rows where income is less than zero and job is not 'Rather not say'
filtered_df = df1[(df1['income'] < 0) & (df1['job'] != 'rather not say')]

count_filtered_rows = len(filtered_df)

print(f"Number of rows with income < 0 and job not 'Rather not say': {count_filtered_rows}")


Number of rows with income < 0 and job not 'Rather not say': 48093


In [45]:
# avrg income by job category 
average_income_by_job = df1[df1['income'] >= 0].groupby('job')['income'].mean().round()

# replace negative income values with  income by job
def replace_negative_income(row):
    if row['income'] < 0:
        job = row['job']
        if job in average_income_by_job:
            return int(average_income_by_job[job])  
    return row['income']


df1['income'] = df1.apply(replace_negative_income, axis=1)


In [46]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59944 entries, 0 to 59945
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   age               59944 non-null  int64         
 1   status            59944 non-null  object        
 2   sex               59944 non-null  object        
 3   orientation       59944 non-null  object        
 4   body_type         54649 non-null  object        
 5   diet              35550 non-null  object        
 6   drinks            56961 non-null  object        
 7   drugs             45865 non-null  object        
 8   education         53317 non-null  object        
 9   ethnicity         54266 non-null  object        
 10  height            59941 non-null  float64       
 11  income            59944 non-null  int64         
 12  job               51747 non-null  object        
 13  last_online       59944 non-null  datetime64[ns]
 14  location          59944 non

In [26]:
# Count rows where 'income' values are less than zero
count_negative_income = (df1['income'] < 0).sum()

print(f"Number of rows with 'income' less than zero: {count_negative_income}")

Number of rows with 'income' less than zero: 0


In [27]:
df1['income'].unique()

array([  85000,   80000,  185256,   20000,  129155,  108365,   74556,
         40000,   99588,   30000,   50000,  105455,  122712,  108924,
         93057,  138815,   85366,   50784,   81583,  101478,   60000,
       1000000,  104051,  150000,  100000,  115899,   91681,  500000,
         91386,   85204,   70000,  250000,  314571])

In [47]:
# Convert 'income' column to integer
df1['income'] = df1['income'].astype(int)

# Export cleaned df

In [33]:
okcupid_cleaned = df1

# Specify the folder path
folder_path = ('/Users/marina/Desktop/final_project/data/cleaned/')

# Specify the file name
file_name = 'okcupid_cleaned.csv'

 #Combine the folder path and file name
file_path = os.path.join(folder_path, file_name)

# Export the DataFrame to a CSV file
okcupid_cleaned.to_csv(file_path, index=False)

print(f'DataFrame exported to {file_path}')



DataFrame exported to /Users/marina/Desktop/final_project/data/cleaned/okcupid_cleaned.csv
